complete_organizations_dict = {
    "Farming for a Brighter Future": {"imageurl": "https://imgur.com/1H7rlXm"},
    "Harvesting Hope Foundation": {"imageurl": "https://imgur.com/9kIODn3"},
    "Green Acres Initiative": {"imageurl": "https://imgur.com/3fNF7x1"},
    "Sustainable Farming Alliance": {"imageurl": "https://imgur.com/Iq1RqDj"},
    "Fields of Growth Foundation": {"imageurl": "https://imgur.com/9UtOlJk"},
    "AgriTech Innovators": {"imageurl": "https://imgur.com/IguysVE"},
    "CropCare Foundation": {"imageurl": "https://imgur.com/fsckTOE"},
    "Farmers Without Borders": {"imageurl": "https://imgur.com/3zXxrIP"},
    "Food Security Network": {"imageurl": "https://imgur.com/NwE0YUr"},
    "Rural Development Alliance": {"imageurl": "https://imgur.com/fh6ly3D"},
    "Animal Guardians Society": {"imageurl": "https://imgur.com/2Su8GLu"},
    "Paws for a Cause": {"imageurl": "https://imgur.com/jN4hv0N"},
    "Wildlife Rescue Team": {"imageurl": "https://imgur.com/Oosm3os"},
    "Furry Friends Foundation": {"imageurl": "https://imgur.com/XjRhRUs"},
    "Humane Society United": {"imageurl": "https://imgur.com/WEDFB32"},
    "Animal Rights Advocates": {"imageurl": "https://imgur.com/mYrDlIE"},
    "Creature Comforts Coalition": {"imageurl": "https://imgur.com/AIAnhwt"},
    "Pet Protection Network": {"imageurl": "https://imgur.com/CAIekzJ"},
    "Save Our Strays": {"imageurl": "https://imgur.com/E2IQ11Q"},
    "Wildlife Conservation Alliance": {"imageurl": "https://imgur.com/3xqZyDQ"},
    "Creative Minds Foundation": {"imageurl": "https://imgur.com/JkHugGa"},
    "Artistic Expressions Society": {"imageurl": "https://imgur.com/fBgvKVp"},
    "Cultural Harmony Collective": {"imageurl": "https://imgur.com/PIkOCXx"},
    "The Artisan Network": {"imageurl": "https://imgur.com/eU2LosW"},
    "Heritage Preservation Trust": {"imageurl": "https://imgur.com/A2hGPxp"},
    "Arts for All Initiative": {"imageurl": "https://imgur.com/Mj1J8DR"},
    "Museums Without Borders": {"imageurl": "https://imgur.com/nDxSu9W"},
    "Music Makers Association": {"imageurl": "https://imgur.com/ahFXOYH"},
    "Performing Arts Alliance": {"imageurl": "https://imgur.com/BFs8xi6"},
    "Visual Arts Foundation": {"imageurl": "https://imgur.com/gdGIi3p"},
    "Youth Empowerment Foundation": {"imageurl": "https://imgur.com/OtckVjf"},
    "Child Education Fund": {"imageurl": "https://imgur.com/SXkn41Q"},
    "Little Explorers Club": {"imageurl": "https://imgur.com/1QHSlva"},
    "Future Leaders Network": {"imageurl": "https://imgur.com/k1PbHyk"},
    "Safe Haven for Kids": {"imageurl": "https://imgur.com/iEoXsqZ"},
    "Child Advocacy Alliance": {"imageurl": "https://imgur.com/nC0PFgG"},
    "Playful Hearts Foundation": {"imageurl": "https://imgur.com/5XC1Jd7"},
    "Children of Tomorrow": {"imageurl": "https://imgur.com/Jxi9oxl"},
    "Equality Advocates Network": {"imageurl": "https://imgur.com/tANm0wv"},
    "Justice for All Foundation": {"imageurl": "https://imgur.com/6N6WO6t"},
    "Social Change Alliance": {"imageurl": "https://imgur.com/anostxD"},
    "Civic Rights Movement": {"imageurl": "https://imgur.com/JTeIntQ"},
    "United Voices Initiative": {"imageurl": "https://imgur.com/2dqHe30"},
    "Citizens for Justice": {"imageurl": "https://imgur.com/GYptXUC"},
    "Equality Now Society": {"imageurl": "https://imgur.com/wBRl8al"},
    "Community Action Network": {"imageurl": "https://imgur.com/EaYweiR"},
    "Civil Liberties Union": {"imageurl": "https://imgur.com/u77k7Hi"},
    "Inclusive Society Project": {"imageurl": "https://imgur.com/v0uz5ds"},
    "Disaster Response Team": {"imageurl": "https://imgur.com/SrtSYcK"},
    "Humanitarian Aid Network": {"imageurl": "https://imgur.com/OChKXng"},
    "Relief Without Borders": {"imageurl": "https://imgur.com/IlqVNvB"},
    "Emergency Relief Corps": {"imageurl": "https://imgur.com/1ANIfcH"},
    "Hope in Crisis Foundation": {"imageurl": "https://imgur.com/Ga4wuxL"},
    "Disaster Resilience Alliance": {"imageurl": "https://imgur.com/b0SxGNx"},
    "Rapid Response Initiative": {"imageurl": "https://imgur.com/rlEcCuw"},
    "Humanitarian Compassion Society": {"imageurl": "https://imgur.com/N01yO8O"},
    "Relief and Recovery Fund": {"imageurl": "https://imgur.com/UzuSO50"},
    "Disaster Relief Volunteers": {"imageurl": "https://imgur.com/SHwXB64"},
    "Economic Empowerment Foundation": {"imageurl": "https://imgur.com/qGmVooL"},
    "Empower Women Now": {"imageurl": "https://imgur.com/iPSpVrG"},
    "Entrepreneurs for Change": {"imageurl": "https://imgur.com/elDaBn5"},
    "Financial Independence Alliance": {"imageurl": "https://imgur.com/nkvAFex"},
    "Small Business Growth Network": {"imageurl": "https://imgur.com/qtkdzPb"},
    "Economic Equality Coalition": {"imageurl": "https://imgur.com/mZdktNc"},
    "Microfinance for All": {"imageurl": "https://imgur.com/eqVT5OR"},
    "Job Opportunities Initiative": {"imageurl": "https://imgur.com/knpx6QA"},
    "Empowerment through Enterprise": {"imageurl": "https://imgur.com/ZDK2sdd"},
    "Economic Inclusion Fund": {"imageurl": "https://imgur.com/3Q5DYPd"},
    "Education for All Foundation": {"imageurl": "https://imgur.com/t0J6Ubn"},
    "Learning Innovators Network": {"imageurl": "https://imgur.com/KDwiMZ6"},
    "Student Success Collaborative": {"imageurl": "https://imgur.com/fn9GYJF"},
    "Pathways to Education": {"imageurl": "https://imgur.com/mQNONJd"},
    "Educators for Change": {"imageurl": "https://imgur.com/hr6SWU8"},
    "Literacy for Life Initiative": {"imageurl": "https://imgur.com/ttdPdEJ"},
    "The Learning Hub": {"imageurl": "https://imgur.com/2vuiOln"},
    "Education Outreach Program": {"imageurl": "https://imgur.com/fcaVnn7"},
    "School Success Network": {"imageurl": "https://imgur.com/9ZofOXC"},
    "Academic Achievement Alliance": {"imageurl": "https://imgur.com/Heb7Pw5"},
    "Scholars of Tomorrow": {"imageurl": "https://imgur.com/R4RX1zM"},
    "Educate the World Foundation": {"imageurl": "https://imgur.com/acD43KJ"},
    "Environment Preservation Society": {"imageurl": "https://imgur.com/bQvwLVy"},
    "Green Earth Alliance": {"imageurl": "https://imgur.com/cmUhKF1"},
    "Conservation Champions": {"imageurl": "https://imgur.com/yf2CcGB"},
    "Nature Protectors Network": {"imageurl": "https://imgur.com/rbOQvDI"},
    "Planet Guardians Foundation": {"imageurl": "https://imgur.com/zFX7VwK"},
    "Wildlife Warriors": {"imageurl": "https://imgur.com/6RBE1Ef"},
    "Ocean Conservation Fund": {"imageurl": "https://imgur.com/fdz4Gzs"},
    "Forest Restoration Initiative": {"imageurl": "https://imgur.com/xXGNc16"},
    "Climate Action Network": {"imageurl": "https://imgur.com/iuFrMJG"},
    "Sustainable Earth Society": {"imageurl": "https://imgur.com/rTlvUXY"},
    "Green Innovations Hub": {"imageurl": "https://imgur.com/DwTjUIL"},
    "Eco-Friendly Future": {"imageurl": "https://imgur.com/SVqYxjr"},
    "Earth Stewards Coalition": {"imageurl": "https://imgur.com/0kF970V"},
    "Nature Conservation Fund": {"imageurl": "https://imgur.com/6WachAv"},
    "Health for All Foundation": {"imageurl": "https://imgur.com/qQxQ210"},
    "Wellness Warriors Network": {"imageurl": "https://imgur.com/f7MHdxA"},
    "Medical Care Outreach": {"imageurl": "https://imgur.com/bz4IwkE"},
    "Healthy Lives Initiative": {"imageurl": "https://imgur.com/rZONAtz"},
    "Healthcare Access Alliance": {"imageurl": "https://imgur.com/9xHL7kP"},
    "Disease Prevention Fund": {"imageurl": "https://imgur.com/g05FAZw"},
    "Mental Health Advocates": {"imageurl": "https://imgur.com/oD1fVjK"},
    "Medical Research Institute": {"imageurl": "https://imgur.com/oxTCss6"},
    "Public Health Partners": {"imageurl": "https://imgur.com/qk7blBD"},
    "Wellness and Healing Society": {"imageurl": "https://imgur.com/J3pdg0u"},
    "Human Rights Advocacy": {"imageurl": "https://imgur.com/c6San42"},
    "Rights and Freedom Network": {"imageurl": "https://imgur.com/XVKIwck"},
    "Global Justice Initiative": {"imageurl": "https://imgur.com/delI8De"},
    "Equality for All Foundation": {"imageurl": "https://imgur.com/NCR9DpY"},
    "Human Dignity Coalition": {"imageurl": "https://imgur.com/sdf56xO"},
    "Freedom Fighters Alliance": {"imageurl": "https://imgur.com/ZI4Hw42"},
    "Human Rights Watchdog": {"imageurl": "https://imgur.com/ekNH07E"},
    "Justice Seekers Network": {"imageurl": "https://imgur.com/aDfVEuD"},
    "Rights Restoration Society": {"imageurl": "https://imgur.com/UyDtcCE"},
    "Liberty and Equality Foundation": {"imageurl": "https://imgur.com/ZzlxYqq"},
    "Political Reform Alliance": {"imageurl": "https://imgur.com/Tx3ehgk"},
    "Civic Engagement Network": {"imageurl": "https://imgur.com/8m9YV8p"},
    "Democracy in Action": {"imageurl": "https://imgur.com/J05vPiy"},
    "Political Transparency Project": {"imageurl": "https://imgur.com/yxkWQy5"},
    "Political Accountability Fund": {"imageurl": "https://imgur.com/aRT96qF"},
    "Public Policy Institute": {"imageurl": "https://imgur.com/Xv7KByw"},
    "Campaign Integrity Coalition": {"imageurl": "https://imgur.com/rHY5KA6"},
    "Electoral Reform Society": {"imageurl": "https://imgur.com/fP7hM73"},
    "Citizens for Good Governance": {"imageurl": "https://imgur.com/SjcFbCx"},
    "Poverty Eradication Initiative": {"imageurl": "https://imgur.com/g3Hrxxj"},
    "Lift Up Lives Foundation": {"imageurl": "https://imgur.com/8VBNXiS"},
    "Anti-Poverty Coalition": {"imageurl": "https://imgur.com/mi47d8C"},
    "Empowerment through Work": {"imageurl": "https://imgur.com/oyKjXSV"},
    "Poverty Alleviation Network": {"imageurl": "https://imgur.com/p15SANw"},
    "Food for All Foundation": {"imageurl": "https://imgur.com/dCO8Dpr"},
    "Housing Opportunities Fund": {"imageurl": "https://imgur.com/7MMgBTY"},
    "Economic Inclusion Initiative": {"imageurl": "https://imgur.com/XND5Yz2"},
    "Poverty Reduction Project": {"imageurl": "https://imgur.com/4dcGCbJ"},
    "Hope for the Homeless": {"imageurl": "https://imgur.com/jgct7KO"},
    "Science for Tomorrow Foundation": {"imageurl": "https://imgur.com/WBBNvxi"},
    "Tech Innovators Network": {"imageurl": "https://imgur.com/WhZtIiu"},
    "Research for Progress Institute": {"imageurl": "https://imgur.com/91PUGFb"},
    "STEM Education Alliance": {"imageurl": "https://imgur.com/BB4XARm"},
    "Tech for Good Foundation": {"imageurl": "https://imgur.com/sJtcAil"},
    "Science Discovery Center": {"imageurl": "https://imgur.com/zEu64Qs"},
    "Innovation Hub Society": {"imageurl": "https://imgur.com/T2vMZRZ"},
    "Technology Access Initiative": {"imageurl": "https://imgur.com/ibni0iF"},
    "Future Scientists Network": {"imageurl": "https://imgur.com/lzuuTYy"},
    "Data Science for Impact": {"imageurl": "https://imgur.com/mZmKzxv"},
    "Social Services Network": {"imageurl": "https://imgur.com/5dkPurk"},
    "Community Support Alliance": {"imageurl": "https://imgur.com/POJlJdz"},
    "Social Welfare Foundation": {"imageurl": "https://imgur.com/XDsETSX"},
    "Supportive Communities Initiative": {"imageurl": "https://imgur.com/VHVHZn4"},
    "Outreach and Assistance Network": {"imageurl": "https://imgur.com/kLL42mZ"},
    "Empowerment through Support": {"imageurl": "https://imgur.com/jourfSk"},
    "Social Impact Advocates": {"imageurl": "https://imgur.com/ZT1bbv4"},
    "Community Care Coalition": {"imageurl": "https://imgur.com/dEhLQzp"},
    "Family Support Network": {"imageurl": "https://imgur.com/OrxtsbS"},
    "Human Services Alliance": {"imageurl": "https://imgur.com/5tVC91n"},
    "Support Our Troops Network": {"imageurl": "https://imgur.com/neYVHSf"},
    "Veteran Health and Wellness": {"imageurl": "https://imgur.com/JNqFWmd"},
    "Military Families United": {"imageurl": "https://imgur.com/Fdx6bdC"},
    "Honoring Heroes Society": {"imageurl": "https://imgur.com/3dwV27g"},
    "Veteran Advocacy Alliance": {"imageurl": "https://imgur.com/YKyCegS"},
    "Veteran Housing Project": {"imageurl": "https://imgur.com/t6Y7Ttj"},
    "Veteran Transition Program": {"imageurl": "https://imgur.com/gFub6Hl"},
    "Service to Veterans Network": {"imageurl": "https://imgur.com/WOay2Ri"}
}